<?php
/**
 * ACF Field Groups
 */

if ( ! defined( constant_name: 'WPINC' ) ) {
    die;
}

add_action( 'acf/include_fields', function(): void {
	if ( ! function_exists( function: 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'qef_simple_location_rules' => 0,
	'key' => 'group_68dcf113ad7e1',
	'title' => 'Job Arbeitsort',
	'fields' => array(
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_68dcf11403af0',
			'label' => 'Ort',
			'name' => 'job_location_place',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Geben Sie hier den Ort als Adresse an.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'placeholder' => 'Ort',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_68dcf1ad9046c',
			'label' => 'PLZ',
			'name' => 'job_location_zip',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Geben Sie hier die Postleitzahl an.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 0,
			'max' => 99999,
			'allow_in_bindings' => 1,
			'placeholder' => 'PLZ',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_68dcf1d89046d',
			'label' => 'Straße und Hausnummer',
			'name' => 'job_location_street',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Geben Sie hier die Straße und Hausnummer an.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'placeholder' => 'Straße und Hausnummer',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68de70b4be3b7',
			'label' => 'Region/Bundesland',
			'name' => 'job_location_region',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Geben Sie hier eine Region oder Bundesland an.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'placeholder' => 'Region oder Bundesland',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_68dcf1ef9046e',
			'label' => 'Land',
			'name' => 'job_location_country',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Geben Sie hier das Land an.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'placeholder' => 'Land',
			'prepend' => '',
			'append' => '',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68de308b46c75',
			'label' => 'Jobs',
			'name' => 'job_location_jobs',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Verknüpfte Stellenangebote.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'job',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 1,
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'bidirectional' => 1,
			'bidirectional_target' => array(
				0 => 'field_68dcf29cdcfbf',
			),
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'job_location',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'slug',
		6 => 'author',
		7 => 'format',
		8 => 'page_attributes',
		9 => 'featured_image',
		10 => 'categories',
		11 => 'tags',
		12 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );

	acf_add_local_field_group( array(
	'qef_simple_location_rules' => 0,
	'key' => 'group_68dbed96a45df',
	'title' => 'Job Details',
	'fields' => array(
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68dbed9787698',
			'label' => 'Kurzbeschreibung',
			'name' => 'job_short_description',
			'wpml_cf_preferences' => 2,
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Hier bitte ein kurze Stellenbeschreibung eingeben.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'rows' => 7,
			'placeholder' => 'Kleine Stellenbeschreibung…',
			'new_lines' => 'br',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 1,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68de7a25cd78d',
			'label' => 'Job Typ',
			'name' => 'job_type',
			'wpml_cf_preferences' => 1,
			'aria-label' => '',
			'type' => 'checkbox',
			'instructions' => 'Wählen Sie die Art der Tätigkeit.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'FULL_TIME' => 'Vollzeit',
				'PART_TIME' => 'Teilzeit',
				'CONTRACTOR' => 'Stelle als Auftragnehmer',
				'TEMPORARY' => 'temporäre Stelle',
				'INTERN' => 'Praktikum',
				'VOLUNTEER' => 'Ehrenamtlich',
				'PER_DIEM' => 'pro Tag bezahlt',
				'OTHER' => 'Ausbildung',
			),
			'default_value' => array(
				0 => 'FULL_TIME',
			),
			'return_format' => 'array',
			'allow_custom' => 0,
			'allow_in_bindings' => 1,
			'layout' => 'horizontal',
			'toggle' => 1,
			'save_custom' => 0,
			'custom_choice_button_text' => 'Eine neue Auswahlmöglichkeit hinzufügen',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68dcea6b9b6fa',
			'label' => 'eigene URL für Stellenagebot (intern oder extern)',
			'name' => 'job_url',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'link',
			'instructions' => 'Wenn das Stellenangebot keine eigene Detailseite besitzen soll, geben Sie bitte hier eine interne oder externe URL ein, zu der die URL der Detailseite weiterleiten soll.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'allow_in_bindings' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 0,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68de45a779674',
			'label' => 'Homeoffice und/oder Präsenzarbeit',
			'name' => 'job_work_type',
			'wpml_cf_preferences' => 1,
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => 'Wählen Sie hier ob die Arbeit im Homeoffice möglich ist, Präsenzarbeit gefordert wird oder beides möglich ist.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'homeoffice' => 'Homeoffice',
				'onsitework' => 'Präsenzarbeit',
				'both' => 'Beides',
			),
			'default_value' => 'onsitework',
			'return_format' => 'array',
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'layout' => 'horizontal',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_68dcf29cdcfbf',
			'label' => 'Arbeitsorte',
			'name' => 'job_location',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Wählen Sie hier einen Arbeitsort aus.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'job_location',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 1,
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'bidirectional' => 1,
			'bidirectional_target' => array(
				0 => 'field_68de308b46c75',
			),
			'ui' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_68dcfa03be81e',
			'label' => 'Firma',
			'name' => 'job_company',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Wählen Sie hier eine Firma aus.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'job_company',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 1,
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'bidirectional' => 1,
			'bidirectional_target' => array(
				0 => 'field_68de31fde1264',
			),
			'ui' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68de5e180b619',
			'label' => 'Grundgehalt',
			'name' => 'job_base_salary_group',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'group',
			'instructions' => 'Angaben zum Grundgehalt.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'allow_backendsearch' => 0,
					'show_column_filter' => false,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_68de693589fde',
					'label' => 'Betrag',
					'name' => 'job_salary',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => 'Geben Sie hier den Betrag des Grundgehalts an.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => '',
					'allow_in_bindings' => 1,
					'placeholder' => 1234,
					'step' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => 0,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_68de69ae89fdf',
					'label' => 'Währung',
					'name' => 'job_salary_currency',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => 'Geben Sie hier die Währung des Grundgehalts an.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'EUR' => '€',
						'USD' => '$',
					),
					'default_value' => 'EUR',
					'return_format' => 'array',
					'multiple' => 0,
					'allow_null' => 0,
					'allow_in_bindings' => 1,
					'ui' => 1,
					'ajax' => 0,
					'placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
				),
				array(
					'allow_backendsearch' => false,
					'show_column_filter' => 0,
					'allow_bulkedit' => 0,
					'allow_quickedit' => 0,
					'show_column' => 0,
					'show_column_weight' => 1000,
					'show_column_sortable' => false,
					'key' => 'field_68de6a2d89fe0',
					'label' => 'Zeitraum',
					'name' => 'job_salary_period',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => 'Geben Sie hier den Zeitraum pro Zahlung an.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'HOUR' => 'pro Stunde',
						'DAY' => 'pro Tag',
						'WEEK' => 'pro Woche',
						'MONTH' => 'pro Monat',
						'YEAR' => 'pro Jahr',
					),
					'default_value' => 'MONTH',
					'return_format' => 'array',
					'multiple' => 0,
					'allow_null' => 0,
					'allow_in_bindings' => 1,
					'ui' => 1,
					'ajax' => 0,
					'placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
				),
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 0,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68de5ae4736be',
			'label' => 'Attribute',
			'name' => 'job_attribute',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => 'Wählen Sie Attribute, Benefits, wie z. B. Parkplatz, Firmenwagen, 4-Tage-Woche etc.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'job-attribute',
			'add_term' => 1,
			'save_terms' => 1,
			'load_terms' => 1,
			'return_format' => 'id',
			'field_type' => 'multi_select',
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 0,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_68dd078cc97de',
			'label' => 'Position vergeben?',
			'name' => 'job_closed',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Für vergebene Positionen können keine Bewerbungen mehr eingereicht werden.',
			'default_value' => 0,
			'allow_in_bindings' => 1,
			'ui_on_text' => 'Ja',
			'ui_off_text' => 'Nein',
			'ui' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 0,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_68dd087603966',
			'label' => 'Hervorgehobenes Stellenagebot?',
			'name' => 'job_featured',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Hervorgehobene Stellenagebote erscheinen bei Suchanfragen oben und können optisch anders dargestellt werden.',
			'default_value' => 0,
			'allow_in_bindings' => 1,
			'ui_on_text' => 'Ja',
			'ui_off_text' => 'Nein',
			'ui' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 1,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => 1,
			'key' => 'field_68dd08cae64be',
			'label' => 'Stellenagebot Ablaufdatum',
			'name' => 'job_expiry_date',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Geben Sie bei Bedarf ein Ablaufdatum an, an dem keine Bewerbungen für dieses Stellenagebot mehr möglich sein sollen.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd.m.Y',
			'return_format' => 'Y-m-d',
			'first_day' => 1,
			'default_to_current_date' => 0,
			'allow_in_bindings' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'job',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );

	acf_add_local_field_group( array(
	'qef_simple_location_rules' => 0,
	'key' => 'group_68dcf8044f518',
	'title' => 'Job Firmendaten',
	'fields' => array(
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68dcf805e6798',
			'label' => 'Firmenwebseite',
			'name' => 'job_company_url',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'link',
			'instructions' => 'Geben Sie hier eine Verlinkung/URL zur Firmenwebseite an.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'allow_in_bindings' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 1,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68dcf8c63df61',
			'label' => 'Firmenlogo',
			'name' => 'job_company_logo',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Wählen Sie hier das Firmenlogo aus.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'return_format' => 'array',
			'library' => 'all',
			'acfe_thumbnail' => 0,
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'allow_in_bindings' => 1,
			'preview_size' => 'thumbnail',
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68de31fde1264',
			'label' => 'Jobs',
			'name' => 'job_company_jobs',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => 'Verknüpfte Stellenangebote.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'job',
			),
			'post_status' => '',
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 1,
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'bidirectional' => 1,
			'bidirectional_target' => array(
				0 => 'field_68dcfa03be81e',
			),
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'job_company',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'slug',
		6 => 'author',
		7 => 'format',
		8 => 'page_attributes',
		9 => 'featured_image',
		10 => 'categories',
		11 => 'tags',
		12 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );

	acf_add_local_field_group( array(
	'qef_simple_location_rules' => 0,
	'key' => 'group_68dd32486c477',
	'title' => 'Job Bewerbung',
	'fields' => array(
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 0,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68dd33fe405cd',
			'label' => 'Beschreibung/Details zu Bewerbungsmöglichkeiten anzeigen?',
			'name' => 'job_application_show_description',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Wählen Sie ob eine Beschreibung in Textform angezeigt werden soll.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'allow_in_bindings' => 1,
			'ui_on_text' => 'Ja',
			'ui_off_text' => 'Nein',
			'ui' => 1,
		),
		array(
			'allow_backendsearch' => 1,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68dd324ae4eaa',
			'label' => 'Beschreibung zu Bewerbungsmöglichkeiten',
			'name' => 'job_application_description',
			'wpml_cf_preferences' => 2,
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Geben Sie hier weiterführende Informationen und Details zu Bewerbungsmöglichkeiten ein.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_68dd33fe405cd',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 1,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 0,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68dd392417e48',
			'label' => '"Jetzt bewerben" Button anzeigen?',
			'name' => 'job_application_show_button',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Wählen Sie ob ein Button, mit wählbarer Verlinkung, angezeigt werden soll?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'allow_in_bindings' => 1,
			'ui_on_text' => 'Ja',
			'ui_off_text' => 'Nein',
			'ui' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68dd3a0f5dfe4',
			'label' => '"Jetzt bewerben" Button',
			'name' => 'job_application_button',
			'wpml_cf_preferences' => 2,
			'aria-label' => '',
			'type' => 'link',
			'instructions' => 'Wählen Sie hier die Beschriftung und die Verlinkung/URL des Buttons.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_68dd392417e48',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'allow_in_bindings' => 1,
		),
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => 0,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68dd39a517e49',
			'label' => '(Formular-)Shortcode anzeigen?',
			'name' => 'job_application_show_shortcode',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Wählen Sie ob ein Shortcode, für z. B. ein Bewerbungsformular, angezeigt werden soll.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'allow_in_bindings' => 1,
			'ui_on_text' => 'Ja',
			'ui_off_text' => 'Nein',
			'ui' => 1,
		),
		array(
			'allow_backendsearch' => 0,
			'show_column_filter' => false,
			'allow_bulkedit' => 0,
			'allow_quickedit' => 0,
			'show_column' => 0,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68dd3a7402384',
			'label' => 'Shortcode',
			'name' => 'job_application_shortcode',
			'wpml_cf_preferences' => 3,
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Geben Sie hier den Shortcode ein.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_68dd39a517e49',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'placeholder' => '[shortcode ...]',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'job',
			),
		),
	),
	'menu_order' => 5,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );

	acf_add_local_field_group( array(
	'qef_simple_location_rules' => 0,
	'key' => 'group_68dd0a3f945a5',
	'title' => 'Job Layout/Inhalt',
	'fields' => array(
		array(
			'allow_backendsearch' => false,
			'show_column_filter' => false,
			'allow_bulkedit' => false,
			'allow_quickedit' => false,
			'show_column' => false,
			'show_column_weight' => 1000,
			'show_column_sortable' => false,
			'key' => 'field_68dd0a4114356',
			'label' => 'Inhalt',
			'name' => 'job_layout_content',
			'wpml_cf_preferences' => 1,
			'aria-label' => '',
			'type' => 'flexible_content',
			'instructions' => 'Erstelle Sie hier eine ausführliche Beschreibung des Stellenangebots, mittels eines kleinen Layout-Editors.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_68dd0a565b15c' => array(
					'key' => 'layout_68dd0a565b15c',
					'name' => 'layout_2_col_text_img',
					'label' => '2-spaltiges Layout (Text links / Bild rechts)',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'allow_backendsearch' => 0,
							'show_column_filter' => false,
							'allow_bulkedit' => false,
							'allow_quickedit' => false,
							'show_column' => false,
							'show_column_weight' => 1000,
							'show_column_sortable' => false,
							'key' => 'field_68dd0bc9e1349',
							'label' => 'Text (links)',
							'name' => 'text_left',
							'wpml_cf_preferences' => 2,
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'allow_in_bindings' => 1,
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'allow_backendsearch' => false,
							'show_column_filter' => false,
							'allow_bulkedit' => 0,
							'allow_quickedit' => 0,
							'show_column' => 0,
							'show_column_weight' => 1000,
							'show_column_sortable' => false,
							'key' => 'field_68dd0bf7e134a',
							'label' => 'Bild (rechts)',
							'name' => 'img_right',
							'wpml_cf_preferences' => 3,
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'uploader' => '',
							'return_format' => 'array',
							'library' => 'all',
							'acfe_thumbnail' => 0,
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 1,
							'preview_size' => 'medium',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68dd0c3fc62c9' => array(
					'key' => 'layout_68dd0c3fc62c9',
					'name' => 'layout_2_col_img_text',
					'label' => '2-spaltiges Layout (Bild links / Text rechts)',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'allow_backendsearch' => false,
							'show_column_filter' => false,
							'allow_bulkedit' => 0,
							'allow_quickedit' => 0,
							'show_column' => 0,
							'show_column_weight' => 1000,
							'show_column_sortable' => false,
							'key' => 'field_68dd0c5dc62cb',
							'label' => 'Bild (links)',
							'name' => 'img_left',
							'wpml_cf_preferences' => 3,
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'uploader' => '',
							'return_format' => 'array',
							'library' => 'all',
							'acfe_thumbnail' => 0,
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 1,
							'preview_size' => 'medium',
						),
						array(
							'allow_backendsearch' => 0,
							'show_column_filter' => false,
							'allow_bulkedit' => false,
							'allow_quickedit' => false,
							'show_column' => false,
							'show_column_weight' => 1000,
							'show_column_sortable' => false,
							'key' => 'field_68dd0c76c62cc',
							'label' => 'Text (rechts)',
							'name' => 'text_right',
							'wpml_cf_preferences' => 2,
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'allow_in_bindings' => 1,
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68dd0d304dce6' => array(
					'key' => 'layout_68dd0d304dce6',
					'name' => 'layout_wysiwyg_full',
					'label' => 'Inhaltseditor über die volle Breite',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'allow_backendsearch' => 0,
							'show_column_filter' => false,
							'allow_bulkedit' => false,
							'allow_quickedit' => false,
							'show_column' => false,
							'show_column_weight' => 1000,
							'show_column_sortable' => false,
							'key' => 'field_68dd0d654dce8',
							'label' => 'Inhaltseditor (volle Breite)',
							'name' => 'wysiwyg_full',
							'wpml_cf_preferences' => 2,
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'allow_in_bindings' => 1,
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => 'Eintrag hinzufügen',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'job',
			),
		),
	),
	'menu_order' => 10,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );
} );
